# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feaf132cad3da27d57b8d32ce05ae249459a6f9fb433b8e94a3521172c93446bc494c35885e630fbf25f874395e61cb66d945862abe99902779bfc13a094c850

test:
  secret_key_base: f68aa577b8c8763fd2e7378ffe0adc00b8a394c95ea83743592f8484f8eb1921b8ea7f3018e7aaf9f9268fa7dd51a43dee10a299de067df63347d29408de6239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
